### ISSUE TITLE
Proposal: add types :list and :non_empty_list

### ISSUE THREAD

**Issue by leandrocp** [dashbitco/nimble_options#28]
I was reviewing this lib as I'd like to try it in a project but I missed checks for lists, so I couldn't properly write some schemas. Sure I could write a custom `{:custom, mod, fun, args}` type but turns out that list is a common type and maybe could be supported out of the box. So, my proposal is to add the types `:list` and `:non_empty_list`, similar to the keyword list pair. Does that make sense? Let me know and I could give a shot sending a PR. Thanks for the lib :)

**Comment by josevalim** [comment]
We would probably need them to be `{:list, ...}` and `{:non_empty_list, ...}`. But I would collect more feedback first, so I would recommend rolling with a custom option for now.

**Comment by whatyouhide** [comment]
I'm on the fence on this one because "complex types" are risky: we'd have to maybe support `:map`, `:enum`, and friends and it might set a dangerous precedent. On the other hand, nimble_options is pragmatic and in my experience with it, I needed to validate lists *a lot* already. So, I'd probably go for it.

My API suggestion:

```elixir
{:list, type, options}
```

where:

  * `type` - any nimble_options type, such as `:string`, `{:custom, mod, fun, args}`, and so on
  * `options`:
    * `:min_length`
    * `:max_length`
    * `:length`

This would avoid having `:non_empty_list` and at the same time be much more flexible. Thoughts?

**Comment by josevalim** [comment]
I would go easy: start with `{:list, type}` and expand if necessary.

**Comment by leandrocp** [comment]
`{:list, type}` sounds good to me. May I work on a PR?

**Comment by whatyouhide** [comment]
@leandrocp yes of course! Feel free to reach out if you need any help 👍
